######################################################################
# Automatically generated by qmake (2.01a) ? 1? 20 19:53:41 2010
######################################################################

TEMPLATE    =  app
TARGET      =  a.out
DEPENDPATH  += .
INCLUDEPATH += . ../../bin/include


# Input
HEADERS += MyWidget.hpp
SOURCES += main.cpp MyWidget.cpp 

CONFIG += opengl debug
QMAKE_CXXFLAGS +=  -Wno-deprecated
QMAKE_CFLAGS +=  -Wno-deprecated
QMAKE_FLAGS +=  -Wno-deprecated


# 
LIBS +=  -L../../bin/lib -lm3g -lQtOpenGL
