SRCS     = $(wildcard *.cpp)
OBJS     = $(SRCS:.cpp=.o)
TARGET   = a.out
CXX      = g++
CXXFLAGS = -Wall -g -Wno-deprecated -I../bin/include
LD       = g++
LDFLAGS  = -L../bin/lib
LIBS     = -lm3g-reader-writer -lz -lUnitTest++

all: $(OBJS)
	$(LD)  $(LDFLAGS) $^ $(LIBS) -o $(TARGET)
	@echo done.

%.o: %.cpp
	$(CXX) $(CXXFLAGS) $< -c

depend:
	makedepend -- $(CXXFLAGS) -- $(SRCS)

clean:
	rm -rf *.o *.so *.a *~ *.out *.m3g log
	@echo done.




# DO NOT DELETE

main.o: /usr/include/unittest++/UnitTest++.h /usr/include/unittest++/Config.h
main.o: /usr/include/unittest++/Test.h /usr/include/unittest++/TestDetails.h
main.o: /usr/include/unittest++/TestList.h
main.o: /usr/include/unittest++/TestSuite.h
main.o: /usr/include/unittest++/TestResults.h
main.o: /usr/include/unittest++/TestMacros.h
main.o: /usr/include/unittest++/ExecuteTest.h
main.o: /usr/include/unittest++/MemoryOutStream.h
main.o: /usr/include/unittest++/AssertException.h
main.o: /usr/include/unittest++/CurrentTest.h
main.o: /usr/include/unittest++/CheckMacros.h
main.o: /usr/include/unittest++/Checks.h /usr/include/unittest++/TestRunner.h
main.o: /usr/include/unittest++/TimeConstraint.h
main.o: /usr/include/unittest++/TimeHelpers.h
test-AnimationController.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-AnimationController.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-AnimationController.o: ../src/InMemoryStream.hpp
test-AnimationController.o: /usr/include/unittest++/UnitTest++.h
test-AnimationController.o: /usr/include/unittest++/Config.h
test-AnimationController.o: /usr/include/unittest++/Test.h
test-AnimationController.o: /usr/include/unittest++/TestDetails.h
test-AnimationController.o: /usr/include/unittest++/TestList.h
test-AnimationController.o: /usr/include/unittest++/TestSuite.h
test-AnimationController.o: /usr/include/unittest++/TestResults.h
test-AnimationController.o: /usr/include/unittest++/TestMacros.h
test-AnimationController.o: /usr/include/unittest++/ExecuteTest.h
test-AnimationController.o: /usr/include/unittest++/MemoryOutStream.h
test-AnimationController.o: /usr/include/unittest++/AssertException.h
test-AnimationController.o: /usr/include/unittest++/CurrentTest.h
test-AnimationController.o: /usr/include/unittest++/CheckMacros.h
test-AnimationController.o: /usr/include/unittest++/Checks.h
test-AnimationController.o: /usr/include/unittest++/TestRunner.h
test-AnimationController.o: /usr/include/unittest++/TimeConstraint.h
test-AnimationController.o: /usr/include/unittest++/TimeHelpers.h
test-AnimationTrack.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-AnimationTrack.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-AnimationTrack.o: ../src/InMemoryStream.hpp
test-AnimationTrack.o: /usr/include/unittest++/UnitTest++.h
test-AnimationTrack.o: /usr/include/unittest++/Config.h
test-AnimationTrack.o: /usr/include/unittest++/Test.h
test-AnimationTrack.o: /usr/include/unittest++/TestDetails.h
test-AnimationTrack.o: /usr/include/unittest++/TestList.h
test-AnimationTrack.o: /usr/include/unittest++/TestSuite.h
test-AnimationTrack.o: /usr/include/unittest++/TestResults.h
test-AnimationTrack.o: /usr/include/unittest++/TestMacros.h
test-AnimationTrack.o: /usr/include/unittest++/ExecuteTest.h
test-AnimationTrack.o: /usr/include/unittest++/MemoryOutStream.h
test-AnimationTrack.o: /usr/include/unittest++/AssertException.h
test-AnimationTrack.o: /usr/include/unittest++/CurrentTest.h
test-AnimationTrack.o: /usr/include/unittest++/CheckMacros.h
test-AnimationTrack.o: /usr/include/unittest++/Checks.h
test-AnimationTrack.o: /usr/include/unittest++/TestRunner.h
test-AnimationTrack.o: /usr/include/unittest++/TimeConstraint.h
test-AnimationTrack.o: /usr/include/unittest++/TimeHelpers.h
test-Appearance.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-Appearance.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-Appearance.o: ../src/InMemoryStream.hpp
test-Appearance.o: /usr/include/unittest++/UnitTest++.h
test-Appearance.o: /usr/include/unittest++/Config.h
test-Appearance.o: /usr/include/unittest++/Test.h
test-Appearance.o: /usr/include/unittest++/TestDetails.h
test-Appearance.o: /usr/include/unittest++/TestList.h
test-Appearance.o: /usr/include/unittest++/TestSuite.h
test-Appearance.o: /usr/include/unittest++/TestResults.h
test-Appearance.o: /usr/include/unittest++/TestMacros.h
test-Appearance.o: /usr/include/unittest++/ExecuteTest.h
test-Appearance.o: /usr/include/unittest++/MemoryOutStream.h
test-Appearance.o: /usr/include/unittest++/AssertException.h
test-Appearance.o: /usr/include/unittest++/CurrentTest.h
test-Appearance.o: /usr/include/unittest++/CheckMacros.h
test-Appearance.o: /usr/include/unittest++/Checks.h
test-Appearance.o: /usr/include/unittest++/TestRunner.h
test-Appearance.o: /usr/include/unittest++/TimeConstraint.h
test-Appearance.o: /usr/include/unittest++/TimeHelpers.h
test-Background.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-Background.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-Background.o: ../src/InMemoryStream.hpp
test-Background.o: /usr/include/unittest++/UnitTest++.h
test-Background.o: /usr/include/unittest++/Config.h
test-Background.o: /usr/include/unittest++/Test.h
test-Background.o: /usr/include/unittest++/TestDetails.h
test-Background.o: /usr/include/unittest++/TestList.h
test-Background.o: /usr/include/unittest++/TestSuite.h
test-Background.o: /usr/include/unittest++/TestResults.h
test-Background.o: /usr/include/unittest++/TestMacros.h
test-Background.o: /usr/include/unittest++/ExecuteTest.h
test-Background.o: /usr/include/unittest++/MemoryOutStream.h
test-Background.o: /usr/include/unittest++/AssertException.h
test-Background.o: /usr/include/unittest++/CurrentTest.h
test-Background.o: /usr/include/unittest++/CheckMacros.h
test-Background.o: /usr/include/unittest++/Checks.h
test-Background.o: /usr/include/unittest++/TestRunner.h
test-Background.o: /usr/include/unittest++/TimeConstraint.h
test-Background.o: /usr/include/unittest++/TimeHelpers.h
test-Camera.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-Camera.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-Camera.o: ../src/InMemoryStream.hpp /usr/include/unittest++/UnitTest++.h
test-Camera.o: /usr/include/unittest++/Config.h
test-Camera.o: /usr/include/unittest++/Test.h
test-Camera.o: /usr/include/unittest++/TestDetails.h
test-Camera.o: /usr/include/unittest++/TestList.h
test-Camera.o: /usr/include/unittest++/TestSuite.h
test-Camera.o: /usr/include/unittest++/TestResults.h
test-Camera.o: /usr/include/unittest++/TestMacros.h
test-Camera.o: /usr/include/unittest++/ExecuteTest.h
test-Camera.o: /usr/include/unittest++/MemoryOutStream.h
test-Camera.o: /usr/include/unittest++/AssertException.h
test-Camera.o: /usr/include/unittest++/CurrentTest.h
test-Camera.o: /usr/include/unittest++/CheckMacros.h
test-Camera.o: /usr/include/unittest++/Checks.h
test-Camera.o: /usr/include/unittest++/TestRunner.h
test-Camera.o: /usr/include/unittest++/TimeConstraint.h
test-Camera.o: /usr/include/unittest++/TimeHelpers.h
test-CompositingMode.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-CompositingMode.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-CompositingMode.o: ../src/InMemoryStream.hpp
test-CompositingMode.o: /usr/include/unittest++/UnitTest++.h
test-CompositingMode.o: /usr/include/unittest++/Config.h
test-CompositingMode.o: /usr/include/unittest++/Test.h
test-CompositingMode.o: /usr/include/unittest++/TestDetails.h
test-CompositingMode.o: /usr/include/unittest++/TestList.h
test-CompositingMode.o: /usr/include/unittest++/TestSuite.h
test-CompositingMode.o: /usr/include/unittest++/TestResults.h
test-CompositingMode.o: /usr/include/unittest++/TestMacros.h
test-CompositingMode.o: /usr/include/unittest++/ExecuteTest.h
test-CompositingMode.o: /usr/include/unittest++/MemoryOutStream.h
test-CompositingMode.o: /usr/include/unittest++/AssertException.h
test-CompositingMode.o: /usr/include/unittest++/CurrentTest.h
test-CompositingMode.o: /usr/include/unittest++/CheckMacros.h
test-CompositingMode.o: /usr/include/unittest++/Checks.h
test-CompositingMode.o: /usr/include/unittest++/TestRunner.h
test-CompositingMode.o: /usr/include/unittest++/TimeConstraint.h
test-CompositingMode.o: /usr/include/unittest++/TimeHelpers.h
test-ExternalReference.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-ExternalReference.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-ExternalReference.o: ../src/InMemoryStream.hpp
test-ExternalReference.o: /usr/include/unittest++/UnitTest++.h
test-ExternalReference.o: /usr/include/unittest++/Config.h
test-ExternalReference.o: /usr/include/unittest++/Test.h
test-ExternalReference.o: /usr/include/unittest++/TestDetails.h
test-ExternalReference.o: /usr/include/unittest++/TestList.h
test-ExternalReference.o: /usr/include/unittest++/TestSuite.h
test-ExternalReference.o: /usr/include/unittest++/TestResults.h
test-ExternalReference.o: /usr/include/unittest++/TestMacros.h
test-ExternalReference.o: /usr/include/unittest++/ExecuteTest.h
test-ExternalReference.o: /usr/include/unittest++/MemoryOutStream.h
test-ExternalReference.o: /usr/include/unittest++/AssertException.h
test-ExternalReference.o: /usr/include/unittest++/CurrentTest.h
test-ExternalReference.o: /usr/include/unittest++/CheckMacros.h
test-ExternalReference.o: /usr/include/unittest++/Checks.h
test-ExternalReference.o: /usr/include/unittest++/TestRunner.h
test-ExternalReference.o: /usr/include/unittest++/TimeConstraint.h
test-ExternalReference.o: /usr/include/unittest++/TimeHelpers.h
test-Fog.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-Fog.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-Fog.o: ../src/InMemoryStream.hpp /usr/include/unittest++/UnitTest++.h
test-Fog.o: /usr/include/unittest++/Config.h /usr/include/unittest++/Test.h
test-Fog.o: /usr/include/unittest++/TestDetails.h
test-Fog.o: /usr/include/unittest++/TestList.h
test-Fog.o: /usr/include/unittest++/TestSuite.h
test-Fog.o: /usr/include/unittest++/TestResults.h
test-Fog.o: /usr/include/unittest++/TestMacros.h
test-Fog.o: /usr/include/unittest++/ExecuteTest.h
test-Fog.o: /usr/include/unittest++/MemoryOutStream.h
test-Fog.o: /usr/include/unittest++/AssertException.h
test-Fog.o: /usr/include/unittest++/CurrentTest.h
test-Fog.o: /usr/include/unittest++/CheckMacros.h
test-Fog.o: /usr/include/unittest++/Checks.h
test-Fog.o: /usr/include/unittest++/TestRunner.h
test-Fog.o: /usr/include/unittest++/TimeConstraint.h
test-Fog.o: /usr/include/unittest++/TimeHelpers.h
test-Group.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-Group.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-Group.o: ../src/InMemoryStream.hpp /usr/include/unittest++/UnitTest++.h
test-Group.o: /usr/include/unittest++/Config.h /usr/include/unittest++/Test.h
test-Group.o: /usr/include/unittest++/TestDetails.h
test-Group.o: /usr/include/unittest++/TestList.h
test-Group.o: /usr/include/unittest++/TestSuite.h
test-Group.o: /usr/include/unittest++/TestResults.h
test-Group.o: /usr/include/unittest++/TestMacros.h
test-Group.o: /usr/include/unittest++/ExecuteTest.h
test-Group.o: /usr/include/unittest++/MemoryOutStream.h
test-Group.o: /usr/include/unittest++/AssertException.h
test-Group.o: /usr/include/unittest++/CurrentTest.h
test-Group.o: /usr/include/unittest++/CheckMacros.h
test-Group.o: /usr/include/unittest++/Checks.h
test-Group.o: /usr/include/unittest++/TestRunner.h
test-Group.o: /usr/include/unittest++/TimeConstraint.h
test-Group.o: /usr/include/unittest++/TimeHelpers.h
test-Header.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-Header.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-Header.o: ../src/InMemoryStream.hpp /usr/include/unittest++/UnitTest++.h
test-Header.o: /usr/include/unittest++/Config.h
test-Header.o: /usr/include/unittest++/Test.h
test-Header.o: /usr/include/unittest++/TestDetails.h
test-Header.o: /usr/include/unittest++/TestList.h
test-Header.o: /usr/include/unittest++/TestSuite.h
test-Header.o: /usr/include/unittest++/TestResults.h
test-Header.o: /usr/include/unittest++/TestMacros.h
test-Header.o: /usr/include/unittest++/ExecuteTest.h
test-Header.o: /usr/include/unittest++/MemoryOutStream.h
test-Header.o: /usr/include/unittest++/AssertException.h
test-Header.o: /usr/include/unittest++/CurrentTest.h
test-Header.o: /usr/include/unittest++/CheckMacros.h
test-Header.o: /usr/include/unittest++/Checks.h
test-Header.o: /usr/include/unittest++/TestRunner.h
test-Header.o: /usr/include/unittest++/TimeConstraint.h
test-Header.o: /usr/include/unittest++/TimeHelpers.h
test-Image2D.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-Image2D.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-Image2D.o: ../src/InMemoryStream.hpp
test-Image2D.o: /usr/include/unittest++/UnitTest++.h
test-Image2D.o: /usr/include/unittest++/Config.h
test-Image2D.o: /usr/include/unittest++/Test.h
test-Image2D.o: /usr/include/unittest++/TestDetails.h
test-Image2D.o: /usr/include/unittest++/TestList.h
test-Image2D.o: /usr/include/unittest++/TestSuite.h
test-Image2D.o: /usr/include/unittest++/TestResults.h
test-Image2D.o: /usr/include/unittest++/TestMacros.h
test-Image2D.o: /usr/include/unittest++/ExecuteTest.h
test-Image2D.o: /usr/include/unittest++/MemoryOutStream.h
test-Image2D.o: /usr/include/unittest++/AssertException.h
test-Image2D.o: /usr/include/unittest++/CurrentTest.h
test-Image2D.o: /usr/include/unittest++/CheckMacros.h
test-Image2D.o: /usr/include/unittest++/Checks.h
test-Image2D.o: /usr/include/unittest++/TestRunner.h
test-Image2D.o: /usr/include/unittest++/TimeConstraint.h
test-Image2D.o: /usr/include/unittest++/TimeHelpers.h
test-InMemoryStream.o: ../src/InMemoryStream.hpp
test-InMemoryStream.o: /usr/include/unittest++/UnitTest++.h
test-InMemoryStream.o: /usr/include/unittest++/Config.h
test-InMemoryStream.o: /usr/include/unittest++/Test.h
test-InMemoryStream.o: /usr/include/unittest++/TestDetails.h
test-InMemoryStream.o: /usr/include/unittest++/TestList.h
test-InMemoryStream.o: /usr/include/unittest++/TestSuite.h
test-InMemoryStream.o: /usr/include/unittest++/TestResults.h
test-InMemoryStream.o: /usr/include/unittest++/TestMacros.h
test-InMemoryStream.o: /usr/include/unittest++/ExecuteTest.h
test-InMemoryStream.o: /usr/include/unittest++/MemoryOutStream.h
test-InMemoryStream.o: /usr/include/unittest++/AssertException.h
test-InMemoryStream.o: /usr/include/unittest++/CurrentTest.h
test-InMemoryStream.o: /usr/include/unittest++/CheckMacros.h
test-InMemoryStream.o: /usr/include/unittest++/Checks.h
test-InMemoryStream.o: /usr/include/unittest++/TestRunner.h
test-InMemoryStream.o: /usr/include/unittest++/TimeConstraint.h
test-InMemoryStream.o: /usr/include/unittest++/TimeHelpers.h
test-KeyframeSequence.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-KeyframeSequence.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-KeyframeSequence.o: ../src/InMemoryStream.hpp
test-KeyframeSequence.o: /usr/include/unittest++/UnitTest++.h
test-KeyframeSequence.o: /usr/include/unittest++/Config.h
test-KeyframeSequence.o: /usr/include/unittest++/Test.h
test-KeyframeSequence.o: /usr/include/unittest++/TestDetails.h
test-KeyframeSequence.o: /usr/include/unittest++/TestList.h
test-KeyframeSequence.o: /usr/include/unittest++/TestSuite.h
test-KeyframeSequence.o: /usr/include/unittest++/TestResults.h
test-KeyframeSequence.o: /usr/include/unittest++/TestMacros.h
test-KeyframeSequence.o: /usr/include/unittest++/ExecuteTest.h
test-KeyframeSequence.o: /usr/include/unittest++/MemoryOutStream.h
test-KeyframeSequence.o: /usr/include/unittest++/AssertException.h
test-KeyframeSequence.o: /usr/include/unittest++/CurrentTest.h
test-KeyframeSequence.o: /usr/include/unittest++/CheckMacros.h
test-KeyframeSequence.o: /usr/include/unittest++/Checks.h
test-KeyframeSequence.o: /usr/include/unittest++/TestRunner.h
test-KeyframeSequence.o: /usr/include/unittest++/TimeConstraint.h
test-KeyframeSequence.o: /usr/include/unittest++/TimeHelpers.h
test-Light.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-Light.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-Light.o: ../src/InMemoryStream.hpp /usr/include/unittest++/UnitTest++.h
test-Light.o: /usr/include/unittest++/Config.h /usr/include/unittest++/Test.h
test-Light.o: /usr/include/unittest++/TestDetails.h
test-Light.o: /usr/include/unittest++/TestList.h
test-Light.o: /usr/include/unittest++/TestSuite.h
test-Light.o: /usr/include/unittest++/TestResults.h
test-Light.o: /usr/include/unittest++/TestMacros.h
test-Light.o: /usr/include/unittest++/ExecuteTest.h
test-Light.o: /usr/include/unittest++/MemoryOutStream.h
test-Light.o: /usr/include/unittest++/AssertException.h
test-Light.o: /usr/include/unittest++/CurrentTest.h
test-Light.o: /usr/include/unittest++/CheckMacros.h
test-Light.o: /usr/include/unittest++/Checks.h
test-Light.o: /usr/include/unittest++/TestRunner.h
test-Light.o: /usr/include/unittest++/TimeConstraint.h
test-Light.o: /usr/include/unittest++/TimeHelpers.h
test-M3GReader.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-M3GReader.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-M3GReader.o: ../src/InMemoryStream.hpp
test-M3GReader.o: /usr/include/unittest++/UnitTest++.h
test-M3GReader.o: /usr/include/unittest++/Config.h
test-M3GReader.o: /usr/include/unittest++/Test.h
test-M3GReader.o: /usr/include/unittest++/TestDetails.h
test-M3GReader.o: /usr/include/unittest++/TestList.h
test-M3GReader.o: /usr/include/unittest++/TestSuite.h
test-M3GReader.o: /usr/include/unittest++/TestResults.h
test-M3GReader.o: /usr/include/unittest++/TestMacros.h
test-M3GReader.o: /usr/include/unittest++/ExecuteTest.h
test-M3GReader.o: /usr/include/unittest++/MemoryOutStream.h
test-M3GReader.o: /usr/include/unittest++/AssertException.h
test-M3GReader.o: /usr/include/unittest++/CurrentTest.h
test-M3GReader.o: /usr/include/unittest++/CheckMacros.h
test-M3GReader.o: /usr/include/unittest++/Checks.h
test-M3GReader.o: /usr/include/unittest++/TestRunner.h
test-M3GReader.o: /usr/include/unittest++/TimeConstraint.h
test-M3GReader.o: /usr/include/unittest++/TimeHelpers.h
test-M3GWriter.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-M3GWriter.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-M3GWriter.o: ../src/InMemoryStream.hpp
test-M3GWriter.o: /usr/include/unittest++/UnitTest++.h
test-M3GWriter.o: /usr/include/unittest++/Config.h
test-M3GWriter.o: /usr/include/unittest++/Test.h
test-M3GWriter.o: /usr/include/unittest++/TestDetails.h
test-M3GWriter.o: /usr/include/unittest++/TestList.h
test-M3GWriter.o: /usr/include/unittest++/TestSuite.h
test-M3GWriter.o: /usr/include/unittest++/TestResults.h
test-M3GWriter.o: /usr/include/unittest++/TestMacros.h
test-M3GWriter.o: /usr/include/unittest++/ExecuteTest.h
test-M3GWriter.o: /usr/include/unittest++/MemoryOutStream.h
test-M3GWriter.o: /usr/include/unittest++/AssertException.h
test-M3GWriter.o: /usr/include/unittest++/CurrentTest.h
test-M3GWriter.o: /usr/include/unittest++/CheckMacros.h
test-M3GWriter.o: /usr/include/unittest++/Checks.h
test-M3GWriter.o: /usr/include/unittest++/TestRunner.h
test-M3GWriter.o: /usr/include/unittest++/TimeConstraint.h
test-M3GWriter.o: /usr/include/unittest++/TimeHelpers.h
test-Material.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-Material.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-Material.o: ../src/InMemoryStream.hpp
test-Material.o: /usr/include/unittest++/UnitTest++.h
test-Material.o: /usr/include/unittest++/Config.h
test-Material.o: /usr/include/unittest++/Test.h
test-Material.o: /usr/include/unittest++/TestDetails.h
test-Material.o: /usr/include/unittest++/TestList.h
test-Material.o: /usr/include/unittest++/TestSuite.h
test-Material.o: /usr/include/unittest++/TestResults.h
test-Material.o: /usr/include/unittest++/TestMacros.h
test-Material.o: /usr/include/unittest++/ExecuteTest.h
test-Material.o: /usr/include/unittest++/MemoryOutStream.h
test-Material.o: /usr/include/unittest++/AssertException.h
test-Material.o: /usr/include/unittest++/CurrentTest.h
test-Material.o: /usr/include/unittest++/CheckMacros.h
test-Material.o: /usr/include/unittest++/Checks.h
test-Material.o: /usr/include/unittest++/TestRunner.h
test-Material.o: /usr/include/unittest++/TimeConstraint.h
test-Material.o: /usr/include/unittest++/TimeHelpers.h
test-Mesh.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-Mesh.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-Mesh.o: ../src/InMemoryStream.hpp /usr/include/unittest++/UnitTest++.h
test-Mesh.o: /usr/include/unittest++/Config.h /usr/include/unittest++/Test.h
test-Mesh.o: /usr/include/unittest++/TestDetails.h
test-Mesh.o: /usr/include/unittest++/TestList.h
test-Mesh.o: /usr/include/unittest++/TestSuite.h
test-Mesh.o: /usr/include/unittest++/TestResults.h
test-Mesh.o: /usr/include/unittest++/TestMacros.h
test-Mesh.o: /usr/include/unittest++/ExecuteTest.h
test-Mesh.o: /usr/include/unittest++/MemoryOutStream.h
test-Mesh.o: /usr/include/unittest++/AssertException.h
test-Mesh.o: /usr/include/unittest++/CurrentTest.h
test-Mesh.o: /usr/include/unittest++/CheckMacros.h
test-Mesh.o: /usr/include/unittest++/Checks.h
test-Mesh.o: /usr/include/unittest++/TestRunner.h
test-Mesh.o: /usr/include/unittest++/TimeConstraint.h
test-Mesh.o: /usr/include/unittest++/TimeHelpers.h
test-MorphingMesh.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-MorphingMesh.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-MorphingMesh.o: ../src/InMemoryStream.hpp
test-MorphingMesh.o: /usr/include/unittest++/UnitTest++.h
test-MorphingMesh.o: /usr/include/unittest++/Config.h
test-MorphingMesh.o: /usr/include/unittest++/Test.h
test-MorphingMesh.o: /usr/include/unittest++/TestDetails.h
test-MorphingMesh.o: /usr/include/unittest++/TestList.h
test-MorphingMesh.o: /usr/include/unittest++/TestSuite.h
test-MorphingMesh.o: /usr/include/unittest++/TestResults.h
test-MorphingMesh.o: /usr/include/unittest++/TestMacros.h
test-MorphingMesh.o: /usr/include/unittest++/ExecuteTest.h
test-MorphingMesh.o: /usr/include/unittest++/MemoryOutStream.h
test-MorphingMesh.o: /usr/include/unittest++/AssertException.h
test-MorphingMesh.o: /usr/include/unittest++/CurrentTest.h
test-MorphingMesh.o: /usr/include/unittest++/CheckMacros.h
test-MorphingMesh.o: /usr/include/unittest++/Checks.h
test-MorphingMesh.o: /usr/include/unittest++/TestRunner.h
test-MorphingMesh.o: /usr/include/unittest++/TimeConstraint.h
test-MorphingMesh.o: /usr/include/unittest++/TimeHelpers.h
test-Node.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-Node.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-Node.o: ../src/InMemoryStream.hpp /usr/include/unittest++/UnitTest++.h
test-Node.o: /usr/include/unittest++/Config.h /usr/include/unittest++/Test.h
test-Node.o: /usr/include/unittest++/TestDetails.h
test-Node.o: /usr/include/unittest++/TestList.h
test-Node.o: /usr/include/unittest++/TestSuite.h
test-Node.o: /usr/include/unittest++/TestResults.h
test-Node.o: /usr/include/unittest++/TestMacros.h
test-Node.o: /usr/include/unittest++/ExecuteTest.h
test-Node.o: /usr/include/unittest++/MemoryOutStream.h
test-Node.o: /usr/include/unittest++/AssertException.h
test-Node.o: /usr/include/unittest++/CurrentTest.h
test-Node.o: /usr/include/unittest++/CheckMacros.h
test-Node.o: /usr/include/unittest++/Checks.h
test-Node.o: /usr/include/unittest++/TestRunner.h
test-Node.o: /usr/include/unittest++/TimeConstraint.h
test-Node.o: /usr/include/unittest++/TimeHelpers.h
test-Object3D.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-Object3D.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-Object3D.o: ../src/InMemoryStream.hpp
test-Object3D.o: /usr/include/unittest++/UnitTest++.h
test-Object3D.o: /usr/include/unittest++/Config.h
test-Object3D.o: /usr/include/unittest++/Test.h
test-Object3D.o: /usr/include/unittest++/TestDetails.h
test-Object3D.o: /usr/include/unittest++/TestList.h
test-Object3D.o: /usr/include/unittest++/TestSuite.h
test-Object3D.o: /usr/include/unittest++/TestResults.h
test-Object3D.o: /usr/include/unittest++/TestMacros.h
test-Object3D.o: /usr/include/unittest++/ExecuteTest.h
test-Object3D.o: /usr/include/unittest++/MemoryOutStream.h
test-Object3D.o: /usr/include/unittest++/AssertException.h
test-Object3D.o: /usr/include/unittest++/CurrentTest.h
test-Object3D.o: /usr/include/unittest++/CheckMacros.h
test-Object3D.o: /usr/include/unittest++/Checks.h
test-Object3D.o: /usr/include/unittest++/TestRunner.h
test-Object3D.o: /usr/include/unittest++/TimeConstraint.h
test-Object3D.o: /usr/include/unittest++/TimeHelpers.h
test-OutMemoryStream.o: ../src/OutMemoryStream.hpp
test-OutMemoryStream.o: /usr/include/unittest++/UnitTest++.h
test-OutMemoryStream.o: /usr/include/unittest++/Config.h
test-OutMemoryStream.o: /usr/include/unittest++/Test.h
test-OutMemoryStream.o: /usr/include/unittest++/TestDetails.h
test-OutMemoryStream.o: /usr/include/unittest++/TestList.h
test-OutMemoryStream.o: /usr/include/unittest++/TestSuite.h
test-OutMemoryStream.o: /usr/include/unittest++/TestResults.h
test-OutMemoryStream.o: /usr/include/unittest++/TestMacros.h
test-OutMemoryStream.o: /usr/include/unittest++/ExecuteTest.h
test-OutMemoryStream.o: /usr/include/unittest++/MemoryOutStream.h
test-OutMemoryStream.o: /usr/include/unittest++/AssertException.h
test-OutMemoryStream.o: /usr/include/unittest++/CurrentTest.h
test-OutMemoryStream.o: /usr/include/unittest++/CheckMacros.h
test-OutMemoryStream.o: /usr/include/unittest++/Checks.h
test-OutMemoryStream.o: /usr/include/unittest++/TestRunner.h
test-OutMemoryStream.o: /usr/include/unittest++/TimeConstraint.h
test-OutMemoryStream.o: /usr/include/unittest++/TimeHelpers.h
test-PolygonMode.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-PolygonMode.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-PolygonMode.o: ../src/InMemoryStream.hpp
test-PolygonMode.o: /usr/include/unittest++/UnitTest++.h
test-PolygonMode.o: /usr/include/unittest++/Config.h
test-PolygonMode.o: /usr/include/unittest++/Test.h
test-PolygonMode.o: /usr/include/unittest++/TestDetails.h
test-PolygonMode.o: /usr/include/unittest++/TestList.h
test-PolygonMode.o: /usr/include/unittest++/TestSuite.h
test-PolygonMode.o: /usr/include/unittest++/TestResults.h
test-PolygonMode.o: /usr/include/unittest++/TestMacros.h
test-PolygonMode.o: /usr/include/unittest++/ExecuteTest.h
test-PolygonMode.o: /usr/include/unittest++/MemoryOutStream.h
test-PolygonMode.o: /usr/include/unittest++/AssertException.h
test-PolygonMode.o: /usr/include/unittest++/CurrentTest.h
test-PolygonMode.o: /usr/include/unittest++/CheckMacros.h
test-PolygonMode.o: /usr/include/unittest++/Checks.h
test-PolygonMode.o: /usr/include/unittest++/TestRunner.h
test-PolygonMode.o: /usr/include/unittest++/TimeConstraint.h
test-PolygonMode.o: /usr/include/unittest++/TimeHelpers.h
test-Section.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-Section.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-Section.o: ../src/InMemoryStream.hpp
test-Section.o: /usr/include/unittest++/UnitTest++.h
test-Section.o: /usr/include/unittest++/Config.h
test-Section.o: /usr/include/unittest++/Test.h
test-Section.o: /usr/include/unittest++/TestDetails.h
test-Section.o: /usr/include/unittest++/TestList.h
test-Section.o: /usr/include/unittest++/TestSuite.h
test-Section.o: /usr/include/unittest++/TestResults.h
test-Section.o: /usr/include/unittest++/TestMacros.h
test-Section.o: /usr/include/unittest++/ExecuteTest.h
test-Section.o: /usr/include/unittest++/MemoryOutStream.h
test-Section.o: /usr/include/unittest++/AssertException.h
test-Section.o: /usr/include/unittest++/CurrentTest.h
test-Section.o: /usr/include/unittest++/CheckMacros.h
test-Section.o: /usr/include/unittest++/Checks.h
test-Section.o: /usr/include/unittest++/TestRunner.h
test-Section.o: /usr/include/unittest++/TimeConstraint.h
test-Section.o: /usr/include/unittest++/TimeHelpers.h
test-SkinnedMesh.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-SkinnedMesh.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-SkinnedMesh.o: ../src/InMemoryStream.hpp
test-SkinnedMesh.o: /usr/include/unittest++/UnitTest++.h
test-SkinnedMesh.o: /usr/include/unittest++/Config.h
test-SkinnedMesh.o: /usr/include/unittest++/Test.h
test-SkinnedMesh.o: /usr/include/unittest++/TestDetails.h
test-SkinnedMesh.o: /usr/include/unittest++/TestList.h
test-SkinnedMesh.o: /usr/include/unittest++/TestSuite.h
test-SkinnedMesh.o: /usr/include/unittest++/TestResults.h
test-SkinnedMesh.o: /usr/include/unittest++/TestMacros.h
test-SkinnedMesh.o: /usr/include/unittest++/ExecuteTest.h
test-SkinnedMesh.o: /usr/include/unittest++/MemoryOutStream.h
test-SkinnedMesh.o: /usr/include/unittest++/AssertException.h
test-SkinnedMesh.o: /usr/include/unittest++/CurrentTest.h
test-SkinnedMesh.o: /usr/include/unittest++/CheckMacros.h
test-SkinnedMesh.o: /usr/include/unittest++/Checks.h
test-SkinnedMesh.o: /usr/include/unittest++/TestRunner.h
test-SkinnedMesh.o: /usr/include/unittest++/TimeConstraint.h
test-SkinnedMesh.o: /usr/include/unittest++/TimeHelpers.h
test-Sprite3D.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-Sprite3D.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-Sprite3D.o: ../src/InMemoryStream.hpp
test-Sprite3D.o: /usr/include/unittest++/UnitTest++.h
test-Sprite3D.o: /usr/include/unittest++/Config.h
test-Sprite3D.o: /usr/include/unittest++/Test.h
test-Sprite3D.o: /usr/include/unittest++/TestDetails.h
test-Sprite3D.o: /usr/include/unittest++/TestList.h
test-Sprite3D.o: /usr/include/unittest++/TestSuite.h
test-Sprite3D.o: /usr/include/unittest++/TestResults.h
test-Sprite3D.o: /usr/include/unittest++/TestMacros.h
test-Sprite3D.o: /usr/include/unittest++/ExecuteTest.h
test-Sprite3D.o: /usr/include/unittest++/MemoryOutStream.h
test-Sprite3D.o: /usr/include/unittest++/AssertException.h
test-Sprite3D.o: /usr/include/unittest++/CurrentTest.h
test-Sprite3D.o: /usr/include/unittest++/CheckMacros.h
test-Sprite3D.o: /usr/include/unittest++/Checks.h
test-Sprite3D.o: /usr/include/unittest++/TestRunner.h
test-Sprite3D.o: /usr/include/unittest++/TimeConstraint.h
test-Sprite3D.o: /usr/include/unittest++/TimeHelpers.h
test-Texture2D.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-Texture2D.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-Texture2D.o: ../src/InMemoryStream.hpp
test-Texture2D.o: /usr/include/unittest++/UnitTest++.h
test-Texture2D.o: /usr/include/unittest++/Config.h
test-Texture2D.o: /usr/include/unittest++/Test.h
test-Texture2D.o: /usr/include/unittest++/TestDetails.h
test-Texture2D.o: /usr/include/unittest++/TestList.h
test-Texture2D.o: /usr/include/unittest++/TestSuite.h
test-Texture2D.o: /usr/include/unittest++/TestResults.h
test-Texture2D.o: /usr/include/unittest++/TestMacros.h
test-Texture2D.o: /usr/include/unittest++/ExecuteTest.h
test-Texture2D.o: /usr/include/unittest++/MemoryOutStream.h
test-Texture2D.o: /usr/include/unittest++/AssertException.h
test-Texture2D.o: /usr/include/unittest++/CurrentTest.h
test-Texture2D.o: /usr/include/unittest++/CheckMacros.h
test-Texture2D.o: /usr/include/unittest++/Checks.h
test-Texture2D.o: /usr/include/unittest++/TestRunner.h
test-Texture2D.o: /usr/include/unittest++/TimeConstraint.h
test-Texture2D.o: /usr/include/unittest++/TimeHelpers.h
test-Transformable.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-Transformable.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-Transformable.o: ../src/InMemoryStream.hpp
test-Transformable.o: /usr/include/unittest++/UnitTest++.h
test-Transformable.o: /usr/include/unittest++/Config.h
test-Transformable.o: /usr/include/unittest++/Test.h
test-Transformable.o: /usr/include/unittest++/TestDetails.h
test-Transformable.o: /usr/include/unittest++/TestList.h
test-Transformable.o: /usr/include/unittest++/TestSuite.h
test-Transformable.o: /usr/include/unittest++/TestResults.h
test-Transformable.o: /usr/include/unittest++/TestMacros.h
test-Transformable.o: /usr/include/unittest++/ExecuteTest.h
test-Transformable.o: /usr/include/unittest++/MemoryOutStream.h
test-Transformable.o: /usr/include/unittest++/AssertException.h
test-Transformable.o: /usr/include/unittest++/CurrentTest.h
test-Transformable.o: /usr/include/unittest++/CheckMacros.h
test-Transformable.o: /usr/include/unittest++/Checks.h
test-Transformable.o: /usr/include/unittest++/TestRunner.h
test-Transformable.o: /usr/include/unittest++/TimeConstraint.h
test-Transformable.o: /usr/include/unittest++/TimeHelpers.h
test-TriangleStripArray.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-TriangleStripArray.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-TriangleStripArray.o: ../src/InMemoryStream.hpp
test-TriangleStripArray.o: /usr/include/unittest++/UnitTest++.h
test-TriangleStripArray.o: /usr/include/unittest++/Config.h
test-TriangleStripArray.o: /usr/include/unittest++/Test.h
test-TriangleStripArray.o: /usr/include/unittest++/TestDetails.h
test-TriangleStripArray.o: /usr/include/unittest++/TestList.h
test-TriangleStripArray.o: /usr/include/unittest++/TestSuite.h
test-TriangleStripArray.o: /usr/include/unittest++/TestResults.h
test-TriangleStripArray.o: /usr/include/unittest++/TestMacros.h
test-TriangleStripArray.o: /usr/include/unittest++/ExecuteTest.h
test-TriangleStripArray.o: /usr/include/unittest++/MemoryOutStream.h
test-TriangleStripArray.o: /usr/include/unittest++/AssertException.h
test-TriangleStripArray.o: /usr/include/unittest++/CurrentTest.h
test-TriangleStripArray.o: /usr/include/unittest++/CheckMacros.h
test-TriangleStripArray.o: /usr/include/unittest++/Checks.h
test-TriangleStripArray.o: /usr/include/unittest++/TestRunner.h
test-TriangleStripArray.o: /usr/include/unittest++/TimeConstraint.h
test-TriangleStripArray.o: /usr/include/unittest++/TimeHelpers.h
test-VertexArray.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-VertexArray.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-VertexArray.o: ../src/InMemoryStream.hpp
test-VertexArray.o: /usr/include/unittest++/UnitTest++.h
test-VertexArray.o: /usr/include/unittest++/Config.h
test-VertexArray.o: /usr/include/unittest++/Test.h
test-VertexArray.o: /usr/include/unittest++/TestDetails.h
test-VertexArray.o: /usr/include/unittest++/TestList.h
test-VertexArray.o: /usr/include/unittest++/TestSuite.h
test-VertexArray.o: /usr/include/unittest++/TestResults.h
test-VertexArray.o: /usr/include/unittest++/TestMacros.h
test-VertexArray.o: /usr/include/unittest++/ExecuteTest.h
test-VertexArray.o: /usr/include/unittest++/MemoryOutStream.h
test-VertexArray.o: /usr/include/unittest++/AssertException.h
test-VertexArray.o: /usr/include/unittest++/CurrentTest.h
test-VertexArray.o: /usr/include/unittest++/CheckMacros.h
test-VertexArray.o: /usr/include/unittest++/Checks.h
test-VertexArray.o: /usr/include/unittest++/TestRunner.h
test-VertexArray.o: /usr/include/unittest++/TimeConstraint.h
test-VertexArray.o: /usr/include/unittest++/TimeHelpers.h
test-VertexBuffer.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-VertexBuffer.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-VertexBuffer.o: ../src/InMemoryStream.hpp
test-VertexBuffer.o: /usr/include/unittest++/UnitTest++.h
test-VertexBuffer.o: /usr/include/unittest++/Config.h
test-VertexBuffer.o: /usr/include/unittest++/Test.h
test-VertexBuffer.o: /usr/include/unittest++/TestDetails.h
test-VertexBuffer.o: /usr/include/unittest++/TestList.h
test-VertexBuffer.o: /usr/include/unittest++/TestSuite.h
test-VertexBuffer.o: /usr/include/unittest++/TestResults.h
test-VertexBuffer.o: /usr/include/unittest++/TestMacros.h
test-VertexBuffer.o: /usr/include/unittest++/ExecuteTest.h
test-VertexBuffer.o: /usr/include/unittest++/MemoryOutStream.h
test-VertexBuffer.o: /usr/include/unittest++/AssertException.h
test-VertexBuffer.o: /usr/include/unittest++/CurrentTest.h
test-VertexBuffer.o: /usr/include/unittest++/CheckMacros.h
test-VertexBuffer.o: /usr/include/unittest++/Checks.h
test-VertexBuffer.o: /usr/include/unittest++/TestRunner.h
test-VertexBuffer.o: /usr/include/unittest++/TimeConstraint.h
test-VertexBuffer.o: /usr/include/unittest++/TimeHelpers.h
test-World.o: ../src/M3GWriter.hpp ../src/OutMemoryStream.hpp
test-World.o: ../src/M3GStruct.hpp ../src/M3GReader.hpp
test-World.o: ../src/InMemoryStream.hpp /usr/include/unittest++/UnitTest++.h
test-World.o: /usr/include/unittest++/Config.h /usr/include/unittest++/Test.h
test-World.o: /usr/include/unittest++/TestDetails.h
test-World.o: /usr/include/unittest++/TestList.h
test-World.o: /usr/include/unittest++/TestSuite.h
test-World.o: /usr/include/unittest++/TestResults.h
test-World.o: /usr/include/unittest++/TestMacros.h
test-World.o: /usr/include/unittest++/ExecuteTest.h
test-World.o: /usr/include/unittest++/MemoryOutStream.h
test-World.o: /usr/include/unittest++/AssertException.h
test-World.o: /usr/include/unittest++/CurrentTest.h
test-World.o: /usr/include/unittest++/CheckMacros.h
test-World.o: /usr/include/unittest++/Checks.h
test-World.o: /usr/include/unittest++/TestRunner.h
test-World.o: /usr/include/unittest++/TimeConstraint.h
test-World.o: /usr/include/unittest++/TimeHelpers.h
